Show more prominently when no team has been defined.

diff --git a/.github/workflows/pelita-runner.yaml b/.github/workflows/pelita-runner.yaml
--- a/.github/workflows/pelita-runner.yaml
+++ b/.github/workflows/pelita-runner.yaml
@@ -20,6 +20,7 @@ jobs:
     runs-on: ubuntu-latest
     outputs:
       team: ${{ steps.set-group-script.outputs.group }}
+      status: ${{ steps.set-group-script.outputs.status }}
     steps:
     - uses: actions/checkout@v2
     - name: Detect group script
@@ -29,15 +30,29 @@ jobs:
         group=($(for g in group{0,1,2,3,4}.py ; do [ -f $g ] && echo "$g" || : ; done ))
         if [ ${#group[@]} -eq 1 ] ; then
           echo "::set-output name=group::\"${group}\""
+          echo "::set-output name=status::\"Run pelita with player from file ${group}\""
         else
-          echo "::error::No or more than one groupN.py file found."
-          echo "::set-output name=group::False"
+          if [ ${#group[@]} -eq 0 ] ; then
+            echo "::error::No groupN.py file found."
+            echo "::set-output name=group::false"
+            echo "::set-output name=status::\"WARNING: No file groupN.py found. Cannot test tournament.\""
+          else
+            echo "::error::More than one groupN.py file found."
+            echo "::set-output name=status::\"Error: More than one groupN.py file found. Cannot test tournament.\""
+            exit 1
+          fi
         fi
       shell: bash
 
   run-pelita:
-    name: Run pelita with player ${{fromJson(needs.detect-team.outputs.team)}}
-    if: ${{fromJson(needs.detect-team.outputs.team)}}
+    # We don’t want CI to fail, when no groupN.py file has been defined, but we
+    # still want to inform the user about this.  Our appraoch is to set the name
+    # of the run-pelita action from the detect-python.
+    name: ${{ fromJson(needs.detect-team.outputs.status) }}
+    # Ideally, we would skip the rest of the action here with an if: clause,
+    # if: ${{ fromJson(needs.detect-team.outputs.team) }}
+    # but this would mean that the expression in name: doesn’t get evaulated either.
+    # Therefore we skip on every single step below.
     needs: detect-team
     runs-on: ubuntu-latest
     strategy:
@@ -47,17 +62,21 @@ jobs:
 
     steps:
     - uses: actions/checkout@v2
+      if: ${{ fromJson(needs.detect-team.outputs.team) }}
     - name: Set up Python ${{ matrix.python-version }}
+      if: ${{ fromJson(needs.detect-team.outputs.team) }}
       uses: actions/setup-python@v2
       with:
         python-version: ${{ matrix.python-version }}
     - name: Install dependencies
+      if: ${{ fromJson(needs.detect-team.outputs.team) }}
       run: |
         python -m pip install --upgrade pip
         python -m pip install flake8 pytest
         python -m pip install git+https://github.com/ASPP/pelita
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
     - name: Check that a the team can be imported
+      if: ${{ fromJson(needs.detect-team.outputs.team) }}
       run: |
         pelita --check-team ${{needs.detect-team.outputs.team}}
 
